#ifndef EG_SPACESIM_NETWORK_ACTION_TYPES_H
#define EG_SPACESIM_NETWORK_ACTION_TYPES_H

#define NETWORK_SERVER_CLIENT_ID 0
#define NETWORK_ACTION_MESSAGE_BROADCAST 5
#define NETWORK_ACTION_MESSAGE_RELAY 6

#endif
